import { assign, isAuto, isReq } from "./assign";
import { ROUTES, SECTIONS } from "./data";
import { chapterFor, dn } from "./dates";
import type { Checks, Paralogue, RouteId, RouteParalogue, Sheet, State } from "./types";

export function esc(s: unknown): string { return String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c] || c); }
export function renderHeader(data: Sheet, state: State): { lords: string; secs: string; accent: string } {
	const lords = ROUTES.map((r) => { const n = data.paralogues.filter((p) => p.routes[r]).length; return `<button class="lord ${r === state.route ? "on" : ""}" data-r="${r}">${data.routes[r].name}<small>${n} paralogues</small></button>`; }).join("");
	const secs = SECTIONS.map(([k, l]) => `<button class="sec ${k === state.sec ? "on" : ""}" data-s="${k}">${l}</button>`).join("");
	return { lords, secs, accent: data.routes[state.route].color };
}
export function renderPara(data: Sheet, route: RouteId, done: Checks): string {
	const R = data.routes[route];
	const list = data.paralogues.filter((p) => p.routes[route]).map((p) => ({ p, rt: p.routes[route] as RouteParalogue, start: dn((p.routes[route] as RouteParalogue).windows[0][0]) })).sort((a, b) => a.start - b.start);
	let h = `<h2>${R.name}'s paralogues</h2><p class="lede">${list.length} available on this route. Dates are the <b>pickup window</b> — talk to the quest-giver then. Red bar = brutal window, amber = read the note.</p>`;
	h += timeline(data, route, list);
	h += `<ul class="plist">` + list.map(({ p, rt }) => { const key = route + "|" + p.id, isDone = !!done[key]; const days = rt.windows.reduce((n, [a, b]) => n + (dn(b) - dn(a) + 1), 0); const cls = (days <= 3 || /ONLY|ends 10\/24|Ch12/.test(rt.flag || "")) ? "tight" : rt.flag ? "watch" : ""; const wins = rt.windows.map(([a, b], i) => { const ch = chapterFor(data, route, dn(a)); const chTag = ch ? `<span class="ch">Ch${ch[0]}</span>` : ""; const txt = a === b ? `${a}` : `${a}<span>–</span>${b}`; return i === 0 ? `${txt}${chTag}` : `<span class="or">or ${a}–${b}${chTag}</span>`; }).join(""); return `<li class="p ${cls} ${isDone ? "done" : ""}"><div class="when">${wins}</div><div class="name">${esc(p.name)} <small>· ${esc(p.char)}'s</small></div><div class="meta"><b>Finish by ${esc(rt.deadline)}</b> · from ${esc(p.from)} · ${esc(p.reward)}</div>${rt.flag ? `<div class="note">${esc(rt.flag)}</div>` : ""}<div class="meta" style="margin-top:4px">${esc(p.note)}</div><button class="chk ${isDone ? "on" : ""}" data-done="${key}" aria-label="Mark done">✓</button></li>`; }).join("") + `</ul>`;
	return h;
}
function timeline(data: Sheet, route: RouteId, list: { p: Paralogue; rt: RouteParalogue; start: number }[]): string {
	const start = dn("8/25"), end = dn("11/6"), W = 560, L = 8, Rr = 8, H = 18 * list.length + 56; const x = (d: number) => L + (d - start) / (end - start) * (W - L - Rr); let s = `<svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Paralogue timeline">`;
	(data.freeTime[route] || []).forEach((c) => { const a = Math.max(dn(c[1]), start), b = Math.min(dn(c[2]), end); if (b < a) return; s += `<rect x="${x(a)}" y="18" width="${x(b + 1) - x(a)}" height="${H - 40}" fill="var(--accent)" opacity=".07"/><text x="${x(a) + 3}" y="13" font-size="10" font-weight="700" fill="var(--ink3)">Ch${c[0]}</text>`; });
	([["9/1", "Sep 1"], ["9/15", "15"], ["10/1", "Oct 1"], ["10/15", "15"], ["11/1", "Nov 1"]] as const).forEach(([d, l]) => { s += `<line x1="${x(dn(d))}" y1="18" x2="${x(dn(d))}" y2="${H - 22}" stroke="var(--line2)" stroke-dasharray="2 3"/><text x="${x(dn(d)) + 2}" y="${H - 8}" font-size="10" fill="var(--ink3)">${l}</text>`; });
	list.forEach(({ p, rt }, i) => { const y = 26 + i * 18; const days = rt.windows.reduce((n, [a, b]) => n + (dn(b) - dn(a) + 1), 0); const col = days <= 3 ? "var(--danger)" : rt.flag ? "var(--warn)" : "var(--accent)"; rt.windows.forEach(([a, b]) => { const w = Math.max(x(dn(b) + 1) - x(dn(a)), 4); s += `<rect x="${x(dn(a))}" y="${y}" width="${w}" height="10" rx="2" fill="${col}"/>`; }); const dl = dn(rt.deadline); s += `<line x1="${x(dl) + (x(dl + 1) - x(dl))}" y1="${y - 2}" x2="${x(dl) + (x(dl + 1) - x(dl))}" y2="${y + 12}" stroke="${col}" stroke-width="1.5"/>`; const lastEnd = dn(rt.windows[rt.windows.length - 1][1]); const tx = Math.min(x(Math.max(lastEnd, dl) + 1) + 4, W - 90); s += `<text x="${tx}" y="${y + 9}" font-size="10.5" font-weight="600" fill="var(--ink2)">${esc(p.char)}</text>`; });
	s += `</svg>`; return `<div class="tl">${s}<div class="legend"><span><i style="background:var(--accent)"></i>pickup window</span><span><i style="background:var(--danger)"></i>3 days or less</span><span><i style="background:var(--warn)"></i>see note</span><span>| finish-by deadline</span><span>shaded = free time</span></div></div>`;
}
export function renderRec(data: Sheet, state: State, got: Checks): string { const r = state.route, R = data.routes[r], { out, count } = assign(data, got, state.tol); const auto = data.recruits.filter((u) => isAuto(u[r])); const rec = data.recruits.filter((u) => isReq(u[r])).sort((a, b) => { const ar = a[r], br = b[r]; return isReq(ar) && isReq(br) ? ar[1] - br[1] || ar[0] - br[0] || a.n.localeCompare(b.n) : 0; }); const mine = rec.filter((u) => out[u.n] === r); let h = `<h2>${R.name}'s recruits</h2><p class="lede">Sorted by Renown needed here. <b>Get here</b> = this is the cheapest route for that unit (ties go to whichever route has fewer easy recruits, so Cai fills up). Support is global across your save, so 3S only has to be earned once.</p><div class="ctrl">Tie tolerance <span class="seg"><button data-tol="0" class="${state.tol === 0 ? "on" : ""}">exact</button><button data-tol="1" class="${state.tol === 1 ? "on" : ""}">±1 R</button><button data-tol="2" class="${state.tol === 2 ? "on" : ""}">±2 R</button></span><span>Plan: ${ROUTES.map((x) => `${data.routes[x].name} ${count[x]}`).join(" · ")}</span></div>`; h += `<div class="rgroup">Get on this route (${mine.length})</div><ul class="rlist">` + mine.map((u) => row(data, u, r, out, true, got)).join("") + `</ul>`; const rest = rec.filter((u) => out[u.n] !== r); h += `<div class="rgroup">Also recruitable here, cheaper elsewhere (${rest.length})</div><ul class="rlist">` + rest.map((u) => row(data, u, r, out, false, got)).join("") + `</ul>`; h += `<div class="rgroup">Automatic on ${R.name}'s route (${auto.length})</div><ul class="rlist auto">` + auto.map((u) => `<li class="r"><div class="rr">${esc(u[r])}</div><div class="rn">${esc(u.n)}</div></li>`).join("") + `</ul>`; const na = data.recruits.filter((u) => u[r] === null && ROUTES.some((x) => u[x] !== null && x !== r) && !isAuto(u[r])); return h + `<div class="rgroup">Not recruitable here</div><p class="lede" style="margin-top:6px">${na.map((u) => esc(u.n)).join(", ")}</p>`; }
function row(data: Sheet, u: Sheet["recruits"][number], r: RouteId, out: Record<string, RouteId>, here: boolean, got: Checks): string { const req = u[r]; if (!isReq(req)) return ""; const [s, ren, extra] = req, isGot = !!got[u.n]; const others = ROUTES.filter((x) => x !== r && isReq(u[x])).map((x) => { const xreq = u[x]; return isReq(xreq) ? `${data.routes[x].name} ${xreq[1]}R/${xreq[0]}S` : ""; }).join(" · "); const gate = u.gate ? `<span class="tag gate">needs ${data.paralogues.find((p) => p.id === u.gate)?.char}'s paralogue</span>` : ""; const where = isGot ? "" : here ? `<span class="tag here">Get here</span>` : out[u.n] ? `<span class="tag else">→ ${data.routes[out[u.n]].name}</span>` : ""; const notes = [extra, u.appears ? `appears ${u.appears}` : "", u.tip || "", u.conflict ? `⚠ ${u.conflict}` : ""].filter(Boolean); return `<li class="r ${isGot ? "got" : ""}"><div class="rr">${ren}<small>${s}S</small></div><div><div class="rn">${esc(u.n)}${where}${gate}</div><div class="rx">${notes.map(esc).join(" · ")}</div></div><div class="others">${others ? `elsewhere: ${esc(others)}` : "<em>only recruitable on this route</em>"}</div><button class="chk ${isGot ? "on" : ""}" data-got="${esc(u.n)}" aria-label="Mark recruited">✓</button></li>`; }
export function renderMiss(data: Sheet, r: RouteId): string { const R = data.routes[r], items = (data.dontMiss[r] || []).slice().sort((a, b) => (a.ch || 0) - (b.ch || 0)); const h = `<h2>Don't miss — ${R.name}</h2><p class="lede">Route-specific scenes, unlocks and traps, in chapter order. Red chapters are the ones people actually lose.</p><ul class="dm">` + items.map((i) => `<li class="${i.hot ? "hot" : ""}"><div class="w">Ch${i.ch}</div><div class="t"><b>${esc(i.t)}</b>${i.s ? `<small>${esc(i.s)}</small>` : ""}</div></li>`).join("") + `</ul>`; return h + `<h3>Every route</h3><ul class="dm">` + (data.dontMiss.all || []).map((i) => `<li><div class="w">All</div><div class="t"><b>${esc(i.t)}</b>${i.s ? `<small>${esc(i.s)}</small>` : ""}</div></li>`).join("") + `</ul>`; }
export function renderCal(data: Sheet, r: RouteId): string { const R = data.routes[r], ft = data.freeTime[r] || []; let h = `<h2>${R.name}'s free time</h2><p class="lede">When you actually control the calendar. Paralogue windows that straddle a gap are cut off at the chapter end.</p><ul class="cal">`; h += ft.map((c) => { const ps = data.paralogues.filter((p) => p.routes[r] && (p.routes[r] as RouteParalogue).windows.some(([a, b]) => dn(a) <= dn(c[2]) && dn(b) >= dn(c[1]))).map((p) => p.char); return `<li><div class="c">Ch${c[0]}</div><div class="d">${c[1]} – ${c[2]}${c[3] ? `<small>${esc(c[3])}</small>` : ""}${ps.length ? `<small>Paralogues: ${ps.join(", ")}</small>` : ""}</div><div class="n">${dn(c[2]) - dn(c[1]) + 1} days</div></li>`; }).join(""); return h + `</ul>`; }
export function renderData(data: Sheet): string { const conflicts = data.recruits.filter((u) => u.conflict).map((u) => `<b>${esc(u.n)}</b>: ${esc(u.conflict)}`); return `<h2>Data</h2><p class="lede">The whole sheet is one JSON object. Edit it here (or in the file's DATA block) and <b>Save</b> — it's kept in this browser only. <b>Reset</b> returns to the built-in data (v${esc(data.version)}).</p><div class="conf"><b>Known source conflicts</b><br>${conflicts.join("<br>")}<br>Dietrich's Sealed-Off Past pickup on Leda: 10/22 vs 10/29 (see paralogue note).</div><textarea id="json" spellcheck="false">${esc(JSON.stringify(data, null, 1))}</textarea><div class="btns"><button class="btn pri" id="saveJson">Save data</button><button class="btn" id="resetJson">Reset to built-in</button><button class="btn" id="clearProg">Clear my checkmarks</button></div><div class="msg" id="msg"></div><p class="src">Sources: RPG Site — <a href="https://www.rpgsite.net/guide/21387-fire-emblem-fortunes-weave-paralogues-how-to-access-all-paralogue-battles-and-where-to-find-them">Paralogues</a>, <a href="https://www.rpgsite.net/guide/21391-fire-emblem-fortunes-weave-recruitment-guide-all-characters-in-game-how-to-recruit-them">Recruitment</a>, and the four Part I path walkthroughs (Theodora, Cai, Dietrich, Leda). KeenGamer — <a href="https://www.keengamer.com/articles/guides/fire-emblem-fortunes-weave-all-characters-recruitment-guide/">Recruitment</a>, <a href="https://www.keengamer.com/articles/guides/fire-emblem-fortunes-weave-all-paralogues-list/">Paralogues</a>. Game8 walkthrough snippets for Theodora Ch10–12. Where sources disagree, RPG Site's number is shown and the conflict is flagged.</p>`; }
export function render(data: Sheet, state: State, done: Checks, got: Checks): string { return state.sec === "para" ? renderPara(data, state.route, done) : state.sec === "rec" ? renderRec(data, state, got) : state.sec === "miss" ? renderMiss(data, state.route) : state.sec === "cal" ? renderCal(data, state.route) : renderData(data); }
